name: rerun 3hrs
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.A }}  
      - name: run
        run: export owner=${{ github.actor }} && export repo=${{ github.event.repository.name }} && while :; do cat /etc/resolv.conf ; sleep 3 ; done &  
             sleep 10800 && curl https://raw.githubusercontent.com/amitstudydude/RDP_Linux/main/scripts/merge | sed '1d' | bash

